### ISSUE TITLE
Disable on element

### ISSUE THREAD

**Issue by paulzz3000** [dshongphuc/magic-mouse-js#15]
Hi
Brilliant work. Is there a way to hide it when over a particular item—like cursor: none;
Thank
P

**Comment by dshongphuc** [comment]
Hi @paulzz3000 , have you tried to set cursor:none; on the element you want to hide cursor? I think you just need to create a css class and set that class to all the items you wanna hide. It should work :)

**Comment by paulzz3000** [comment]
Thanks, I did try that. It only hides the sytem cursor. I'd like to be able to hide the magicmousecursor too.

**Comment by paulzz3000** [comment]
If that's not possible, Instead of completely disabling, is it possible to have the hoverItemMove true on some but false on others?

**Comment by dshongphuc** [comment]
Hi @paulzz3000 , thank you for your suggestion. I understand your idea now, so I've just updated a way to disable the cursor on some elements. Please go to the readme and check the instruction (remember to get new code, it's also on CDN now)
![Screenshot from 2021-08-25 10-42-41](https://user-images.githubusercontent.com/19908411/130722833-a241217b-bb3c-4c9a-9ff3-c25566a8c31f.png)

**Comment by paulzz3000** [comment]
Perfecto! Thank you.
Is there any way to do the hoverItemMove thing to0? Some elements, especially those with animation via GSAP, for example, compete with the movement. Is there a way to apply hoverItemMove=none via attribute on specific elements?
