### ISSUE TITLE
Standard cursor on OS

### ISSUE THREAD

**Issue by MrZer0Fr0sty** [dshongphuc/magic-mouse-js#24]
How to add it on my system? Because as I know, there is must be a special file type. Sooo, what should I do, to make it .CUR (or other if they exist) type file?

**Comment by dshongphuc** [comment]
@MrZer0Fr0sty Interesting. You mean to integrate this package into your OS? Unfortunately, I don't have any experience in OS development so I don't have the answer for you. But if you found the solution yourself, please share it with us :)

**Comment by dshongphuc** [comment]
Close due to inactivity
