### ISSUE TITLE
Unable to `customize` cursor

### ISSUE THREAD

**Issue by realhackcraft** [dshongphuc/magic-mouse-js#31]
I have a completely white UI and want to change the cursor colour to `rgb(175, 175, 175)`(grey). I used the cdn.min.js file, and changed the `magic-mouse.css`. The changes do not reflect on my page.

**Comment by dshongphuc** [comment]
hi @realhackcraft , all you need to do is change style for the `body #magicPointer` and `body #magicMouseCursor`

**Comment by realhackcraft** [comment]
There is no effect if I do that on the newest version. However, when I copied the magic-cursor.js from https://www.lucammello.com<https://www.lucammello.com/>, I can get it to work.

From: Phuc H. ***@***.***>
Date: Friday, October 7, 2022 at 10:42 PM
To: dshongphuc/magic-mouse-js ***@***.***>
Cc: realhackcraft ***@***.***>, Mention ***@***.***>
Subject: Re: [dshongphuc/magic-mouse-js] Unable to `customize` cursor (Issue #31)

hi @realhackcraft<https://github.com/realhackcraft> , all you need to do is change style for the body #magicPointer and body #magicMouseCursor

**Comment by realhackcraft** [comment]
[magic_mouse.js.zip](https://github.com/dshongphuc/magic-mouse-js/files/9739832/magic_mouse.js.zip)
This one works, and the one included in your repo does not.

**Comment by realhackcraft** [comment]
I cannot customize the colour because at the beginning there is `const STYLE` and you set the style of the cursor there, I think.

**Comment by realhackcraft** [comment]
from 5:255 to 5:1215

**Comment by dshongphuc** [comment]
@realhackcraft Thank you for sharing, did you try to add `!important` to your styles?

**Comment by realhackcraft** [comment]
can you show me an example? im bad at css

**Comment by dshongphuc** [comment]
@realhackcraft For example if you want to change the border & background of the cursor to red color:
```
body #magicMouseCursor {
  border: 1px solid red !important;
}
body #magicPointer {
  background: red !important;
}
```

**Comment by realhackcraft** [comment]
what does !important mean?

**Comment by dshongphuc** [comment]
@realhackcraft well, in css, we have priority of selector. So if a selector has an `!important` property, it will have the highest priority. Basically you use that to override my CSS in magicmouse.js file

**Comment by realhackcraft** [comment]
![image](https://user-images.githubusercontent.com/65378120/195347281-533bfac1-9aa6-4150-98ed-a5a477cc3e99.png)
