### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by tomoyanime** [dshongphuc/magic-mouse-js#37]
### Subject of the issue
The download link on the homepage doesn't let me download the file.

### Steps to reproduce
- Go to the homepage. https://magicmousejs.web.app/
- Click the Download button. https://magicmousejs.web.app/dist/magicmouse-1.0.zip
- Cannot download the zip file.

### Expected behaviour
I should be able to download the zip file.

### Actual behaviour
https://magicmousejs.web.app/dist/magicmouse-1.0.zip just returns a web page instead of the zip file.

**Comment by dshongphuc** [comment]
Hi @tomoyanime , thank you so much for letting me know the issue. Yes the web page is outdated, I'll update the link when I came back home but now please download it from github instead.

**Comment by dshongphuc** [comment]
Fixed
