### ISSUE TITLE
Hover class for #magicMouseCursor

### ISSUE THREAD

**Issue by felixdorner** [dshongphuc/magic-mouse-js#4]
Hey Phuc,

thanks for your great script. For my desired style, I did set the "defaultCursor" option to true and display the outer circle only. Now I'd like to set a hover effect with CSS, but there is no hover class added to the #magicMouseCursor div when hovering over a link? Can you help me out to target the hover of the #magicMouseCursor div?

Cheers,
Felix

**Comment by dshongphuc** [comment]
Hi @felixdorner ,
My apologizes for replying your issue too late, I didn't see notification.
For your issue, I think the #magicMouseCursor div already have the class name "is-hover" when it hover to something, you can open the dev tool and check on homepage.

Thanks,
Phuc.

**Comment by felixdorner** [comment]
Hey @dshongphuc, thanks for your answer but I went with a different solution. 

However, as I remember correctly, I did check it with dev tools and there was no "is-hover" class for #magicMouseCursor... only for its child divs (outer circle and cursor). But I would need to check again and as mentioned before, I found another solution. Thanks.
