### ISSUE TITLE
Cursor copy sticks in header

### ISSUE THREAD

**Issue by calinxradu** [dshongphuc/magic-mouse-js#5]
Hello,

First of all, I want to thank you for the plugin, it's really cool. I'm trying to build my website at the moment and I found this issue with the cursor. A fixed copy of it sticks in the header of the page. Do you know what would be causing this? 

[www.calrad.dreamhosters.com](url)

Thank you very much in advance!

**Comment by dshongphuc** [comment]
Hi @calinxradu , thank you for your warm comment :) 
I view the source code of your website and I think the problem is that you integrated Magicmouse multiple times in your site. You can view the source code of your page and search for "magicMouse(options)" to see what I mean, please remove all and just keep one.

Hope it help :)

**Comment by calinxradu** [comment]
Thank you very much for your help mate! It worked!

**Comment by calinxradu** [comment]
Hey @dshongphuc, 

It's me again XD. I followed your instructions and managed to fix it, but now I'm confronted with the same error, but only on tablet & mobile. 

If you inspect it looks alright, but when I go on the website on my mobile and my tablet, the cursor still appears, stuck in the top left corner of the header. Any ideas why it's not disabled on mobile and tablet?

Thank you in advance!

**Comment by dshongphuc** [comment]
Hi @calinxradu , I believe the magicmouse.js on your site is outdated version, please update to this : https://res.cloudinary.com/veseylab/raw/upload/v1597754761/magicmouse/magic_mouse-1.0.js
Or download the latest code from this repo, the file located at dist/magic_mouse.js

**Comment by calinxradu** [comment]
Thank you very much, it worked! Though I had to change the screen width to 1024 to work on my iPad Pro. 

Many thanks again!
