### ISSUE TITLE
Set Select tag Cursor to pointer by default

### ISSUE THREAD

**Issue by tonalmathew** [dshongphuc/magic-mouse-js#51]

**Comment by dshongphuc** [comment]
Hi @tonalmathew  thanks for opening the issue, can you please explain a little bit more? I don't think I understand what you mean about the default tag?

**Comment by dshongphuc** [comment]
@tonalmathew Yes because I didn't add the class `magic-hover magic-hover__square` to that select, I'll do that, thanks for reminding me @tonalmathew
