### ISSUE TITLE
Not working properly on Safari

### ISSUE THREAD

**Issue by salehriaz** [dshongphuc/magic-mouse-js#6]
Hi, as much as I love this library, the #magicMouseCursor does not work properly on safari.
It doesn't follow the dot cursor properly and seems to get stuck.

**Comment by dshongphuc** [comment]
Hi @salehriaz , thank you for your report. I'm not a Mac user so I've not tested this libs on Safari, I will try to find a way to test it and hope we can fix this issue soon.

**Comment by salehriaz** [comment]
Its the transition property of the #magicMouseCursor is what makes it act this way.
For now, I just remove transition. It works fine now.

**Comment by dshongphuc** [comment]
@salehriaz Thank you, may I know what is the version of your Safari? I tested it on version 12 and seems it works well.

**Comment by dshongphuc** [comment]
Close due to inactivity
