### ISSUE TITLE
Not Working on Firefox

### ISSUE THREAD

**Issue by whiteyhat** [dshongphuc/magic-mouse-js#9]
https://user-images.githubusercontent.com/31220861/105861657-3e2ea980-5fef-11eb-962e-69306ff44132.mov

**Comment by whiteyhat** [comment]
Sure! @cborlado, can you actually report more details about this problem?

**Comment by cborlado** [comment]
What do you mean? The animations in our site? If so the rifle you see in the left hand side is just a 3D GLB viewer. The image  on the right where the mouse is trembling is just a static image.

However if you are asking for any settings of the magicmouse add-on that can be configured by the user (not sure if that's possible), I would have to redirect you back again to @whiteyhat

**Comment by whiteyhat** [comment]
@cborlado just describe your experience as well as the video, it happens in all areas? It keeps happening if so record another video 😄

**Comment by dshongphuc** [comment]
Do you have any demo account or something for me to access and test it inside? @cborlado @whiteyhat

**Comment by cborlado** [comment]
@dshongphuc send over an email address to give you access to the platform so that you can test by yoursef

**Comment by dshongphuc** [comment]
@cborlado this is my email : dshongphuc@gmail.com

**Comment by cborlado** [comment]
Done

**Comment by dshongphuc** [comment]
@cborlado @whiteyhat I cannot replicate your issue on my browsers (tested on Firefox and Chrome)
https://user-images.githubusercontent.com/19908411/106339553-8688e880-62c9-11eb-99c9-743c5298b9b7.mp4

**Comment by whiteyhat** [comment]
> @cborlado @whiteyhat I cannot replicate your issue on my browsers (tested on Firefox and Chrome)

Oh I see, maybe it was a weird resolution from @cborlado side 😮 

I will close this and re-open it any user has the same issue
